---
# Purpose: Creates user and password using variables from Ansible Vault files
# Modules Used: user & shell
# Pre-Requisite Steps can be found at - ansible_vault_user_password_steps.txt

- name: ansible_vault_user_password
  hosts: ansible1
  vars_files:
     - lab5/user
     - lab5/password
  tasks:
     - name: create {{ user }}
       user:
          name: “{{ user }}”
     - shell: echo {{ password }} | passwd --stdin {{ user }}
