---
# Purpose: Conditional Control Play Execution - dependent on Memory available on Host
# Modules Used: fail & sysctl

- name: conditional_play_execution
  hosts: all
  tasks: 
   - name:
     fail:
       msg: Server memory less than 2048MB >>> {{ ansible_memtotal_mb }}
     when: ansible_memtotal_mb < 2048
   - name:
     sysctl:
       name: vm.swappiness
       value: '10'
       state: present
     when: ansible_memtotal_mb > 2048
