---
# Purpose: RHEL System Role configures time synchronisation against the pool.ntp.org time servers (to be used alongside the rhel-system-roles.timesync role)
# Modules Used: timezone

- name: rhel-system-roles.timesync
  hosts: all
  vars: 
    timesync_ntp_servers:
      - hostname: 0.rhel.pool.ntp.org
        iburst: yes
    timezone: UTC 
  roles:
  - rhel-system-roles.timesync
  tasks:
    - name:
      timezone:
        name: "{{ timezone }}"
