---
# Purpose: Generates specs_report.txt file (to be used with the specs.j2 file)
# Modules Used: template
- name: specs_report_jinja_template
  hosts: all 
  tasks:
    - name:
      template:
        src: specs.j2
        dest: /root/specs_report.txt