---
# Purpose: Generates an /etc/hosts file (to be used with the hosts.j2 file)
# Modules Used: template

- name: etc_hosts_jinja_template
  hosts: all
  tasks:
    - name:
      template:
        src: hosts.j2
        dest: /etc/hosts
