---
# tasks file for webconfig
- dnf:
    name:
      - httpd
      - firewalld
    state: latest
- service:
    name: "{{ httpd_service }}"
    state: started
    enabled: yes
- service:
    name: firewalld
    state: started 
    enabled: yes
- firewalld:
    service: http
    port: "{{ http_port }}"
    state: enabled
    permanent: true
    immediate: true
- template:
    src: index.html.j2
    dest: "{{ index_path }}"
  notify: restart
